### ISSUE TITLE
[Help wanted ] Installation  failed

### ISSUE THREAD

**Issue by timfaner** [nervosnetwork/lumos#159]
Trying to install lumos but got error, maybe some dependencies are missing ?

``` shell
yarn install v1.22.11
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[-/4] ⠠ waiting...
[-/4] ⠠ waiting...
[4/4] ⠠ @ckb-lumos/indexer
error /root/test/lumos/node_modules/@ckb-lumos/indexer: Command failed.
Exit code: 1
Command: node scripts/install_binary.js || npm run build-release
Arguments:
Directory: /root/test/lumos/node_modules/@ckb-lumos/indexer
Output:
node-pre-gyp args: install --fallback-to-build=false
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.14.0
node-pre-gyp info using node@16.6.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/root/test/lumos/packages/indexer/native/index.node" (not found)
node-pre-gyp http GET https://github.com/nervosnetwork/lumos/releases/download/v0.16.0/lumos-indexer-node-v93-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/nervosnetwork/lumos/releases/download/v0.16.0/lumos-indexer-node-v93-linux-x64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/nervosnetwork/lumos/releases/download/v0.16.0/lumos-indexer-node-v93-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/root/test/lumos/node_modules/node-pre-gyp/lib/install.js:142:27)
node-pre-gyp ERR! stack     at Request.emit (node:events:406:35)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/root/test/lumos/node_modules/request/request.js:1059:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (node:events:394:28)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:621:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (node:_http_client:487:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (node:events:394:28)
node-pre-gyp ERR! stack     at addChunk (node:internal/streams/readable:312:12)
node-pre-gyp ERR! stack     at readableAddChunk (node:internal/streams/readable:287:9)
node-pre-gyp ERR! System Linux 4.15.0-88-generic
node-pre-gyp ERR! command "/usr/bin/node" "/root/test/lumos/node_modules/@ckb-lumos/indexer/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /root/test/lumos/packages/indexer
node-pre-gyp ERR! node -v v16.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
404 status code downloading tarball https://github.com/nervosnetwork/lumos/releases/download/v0.16.0/lumos-indexer-node-v93-linux-x64.tar.gz
Exec error, code: 1, stderr:

> @ckb-lumos/indexer@0.16.0 build-release
> neon build --release

neon ERR! spawn cargo ENOENT

Error: spawn cargo ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
```

**Comment by timfaner** [comment]
Node.js 16 is not supported. Use Node.js 14 (LTS)
