### ISSUE TITLE
Overflow occurs when lumos deploys auth contract

### ISSUE THREAD

**Issue by 15168316096** [nervosnetwork/lumos#579]
## Bug Report
Overflow occurs when lumos deploys auth contract
source scirpt code:[auth.c](https://github.com/nervosnetwork/ckb-auth/blob/main/c/auth.c)
bin:[auth.zip](https://github.com/ckb-js/lumos/files/13578538/auth.zip)

### Expected Behavior
I expect normal when lumos deploys auth contract

### Environment
* **CKB version**:  [v0.112.1](https://github.com/nervosnetwork/ckb/tree/v0.112.1)
 * **Chain**: /
 * **Operating system**: `MacOS 12.1`
 * **Arch**: x64
 * **Installation**: Built from source
 
 ### Additional context/Screenshots
 This bug can reproduced by these steps:

 ```

 public async deployContract(options: {
    account: Account,
    contractName: string,
    contractPath: string,
    deployType: HashType
  }) {
    const contractBuffer = readFileSync(options.contractPath);
    console.log("contract length:", contractBuffer.length)
    let deployResult: {
      txSkeleton: TransactionSkeletonType;
      scriptConfig: ScriptConfig;
    };

    // switch (options.deployType) {
    if (options.deployType == "type") {
      deployResult = await deploy.generateDeployWithTypeIdTx(
          {
            cellProvider: this.indexer,
            scriptBinary: contractBuffer,
            fromInfo: options.account.address,
          });
      deployResult.scriptConfig.HASH_TYPE = options.deployType
      console.log(deployResult.scriptConfig.TX_HASH)
      this.updateConfigFile(options.contractName, deployResult.scriptConfig)
    } else if (options.deployType == "data" || options.deployType == "data1" || options.deployType == "data2") {
      deployResult = await deploy.generateDeployWithDataTx(
          {
            cellProvider: this.indexer,
            scriptBinary: contractBuffer,
            fromInfo: options.account.address,
          });
      deployResult.scriptConfig.HASH_TYPE = options.deployType
      console.log(deployResult.scriptConfig.TX_HASH)
      this.updateConfigFile(options.contractName, deployResult.scriptConfig)
    } else {
      throw new Error("not support")
    }


    // @ts-ignore
    let txSkeleton = common.prepareSigningEntries(deployResult.txSkeleton);
    const message = txSkeleton.get("signingEntries").get(0)?.message;
    const Sig = key.signRecoverable(message!, options.account.privKey);
    const tx = sealTransaction(txSkeleton, [Sig]);
    let tx_hash = await this.rpc.sendTransaction(tx, "passthrough");
    console.log('deploy hash:', tx_hash)
    return tx_hash
  }

#  Overflow occurs when lumos deploys auth contract
#  stack trace: contract name: auth  hash 0xcd68f68f36d832ea5758e50c3cebaf7eaab733ad4029afa54aab78d4c54e9f71
contract length: 6587624
/Users/xueyanli/IdeaProjects/CKB-Contract-Data-Simulator/lumos/packages/codec/src/utils.ts:45
    if (!HEX_STRING_REGEX.test(str)) {
                          ^
RangeError: Maximum call stack size exceeded
    at assertHexString (/Users/xueyanli/IdeaProjects/CKB-Contract-Data-Simulator/lumos/packages/codec/src/utils.ts:45:27)
    at bytifyHex (/Users/xueyanli/IdeaProjects/CKB-Contract-Data-Simulator/lumos/packages/codec/src/bytes.ts:18:18)
    at bytify (/Users/xueyanli/IdeaProjects/CKB-Contract-Data-Simulator/lumos/packages/codec/src/bytes.ts:45:45)
    at minimalCellCapacityCompatible (/Users/xueyanli/IdeaProjects/CKB-Contract-Data-Simulator/lumos/packages/helpers/src/index.ts:87:14)
    at updateOutputs (/Users/xueyanli/IdeaProjects/CKB-Contract-Data-Simulator/lumos/packages/common-scripts/src/deploy.ts:56:53)
    at Object.generateDeployWithTypeIdTx (/Users/xueyanli/IdeaProjects/CKB-Contract-Data-Simulator/lumos/packages/common-scripts/src/deploy.ts:541:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E2EProvider.deployContract (/Users/xueyanli/IdeaProjects/CKB-Contract-Data-Simulator/src/e2eProvider.ts:555:22)
    at async main (/Users/xueyanli/IdeaProjects/CKB-Contract-Data-Simulator/scripts/deploy.ts:83:18)
 ```

**Comment by homura** [comment]
hi, @15168316096 it would be great if you could provide a compiled version of the `auth.c`, this will save us lots of time

**Comment by homura** [comment]
> contract length: 6587624

I found that the contract size 6,587,624(6.587624 MB) exceeds the `MAX_BLOCK_BYTES` 597,000(0.597 MB) from the [CKB consensus](https://github.com/nervosnetwork/ckb/blob/develop/spec/src/consensus.rs#L82). Is there something wrong with the compilation of this contract?

**Comment by 15168316096** [comment]
The auth bin file has been updated

**Comment by 15168316096** [comment]
> > contract length: 6587624
> 
> I found that the contract size 6,587,624(6.587624 MB) exceeds the `MAX_BLOCK_BYTES` 597,000(0.597 MB) from the [CKB consensus](https://github.com/nervosnetwork/ckb/blob/develop/spec/src/consensus.rs#L82). Is there something wrong with the compilation of this contract?

have to use capsule build --release to compile instead of the debug version. The release version is about 50KB when compiled, so this problem can be solved.

```
deploy hash: 0x0b92f15a2b0ac0f05ab941b039ddd6811590d328954be8d5595037e88c344513
contract name: auth  hash 0x0b92f15a2b0ac0f05ab941b039ddd6811590d328954be8d5595037e88c344513
contractPath: source/contracts/auth-rust-demo
contract length: 51144
0xea64ba4b45a0f6c05994419e6759c8414684d40add6b0a1600edc569415b4b4b
[warn] `config` changed, regenerate lockScriptInfos!
deploy hash: 0xea64ba4b45a0f6c05994419e6759c8414684d40add6b0a1600edc569415b4b4b
contract name: auth-rust-demo  hash 0xea64ba4b45a0f6c05994419e6759c8414684d40add6b0a1600edc569415b4b4b
deploy successful
```

**Comment by 15168316096** [comment]
> > contract length: 6587624
> 
> I found that the contract size 6,587,624(6.587624 MB) exceeds the `MAX_BLOCK_BYTES` 597,000(0.597 MB) from the [CKB consensus](https://github.com/nervosnetwork/ckb/blob/develop/spec/src/consensus.rs#L82). Is there something wrong with the compilation of this contract?

can use the limit value close to the consensus to verify the performance of the tool function.
