### ISSUE TITLE
Cyclic dependency of ckb-debugger package

### ISSUE THREAD

**Issue by XuJiandong** [nervosnetwork/lumos#618]
**To Reproduce**
```
❯ pwd
~/projects/lumos/examples/misc

❯ npx babel --root-mode upward ./ --out-dir lib --extensions .ts -s
Error: ENAMETOOLONG: name too long, stat 'node_modules/@ckb-lumos/lumos/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/config-manager/node_modules/@ckb-lumos/base/node_modules/@ckb-lumos/codec/node_modules/@ckb-lumos/bi/node_modules/jsbi/dist/jsbi-cjs.js.map'
    at Object.statSync (node:fs:1666:25)
    at /Users/xjd/projects/lumos/node_modules/.pnpm/@babel+cli@7.16.7_@babel+core@7.16.7/node_modules/@babel/cli/lib/babel/util.js:78:24
    at /Users/xjd/projects/lumos/node_modules/.pnpm/fs-readdir-recursive@1.1.0/node_modules/fs-readdir-recursive/index.js:16:14
    at Array.filter (<anonymous>)
    at read (/Users/xjd/projects/lumos/node_modules/.pnpm/fs-readdir-recursive@1.1.0/node_modules/fs-readdir-recursive/index.js:15:6)
    at /Users/xjd/projects/lumos/node_modules/.pnpm/fs-readdir-recursive@1.1.0/node_modules/fs-readdir-recursive/index.js:19:7
    at Array.forEach (<anonymous>)
    at read (/Users/xjd/projects/lumos/node_modules/.pnpm/fs-readdir-recursive@1.1.0/node_modules/fs-readdir-recursive/index.js:18:6)
    at /Users/xjd/projects/lumos/node_modules/.pnpm/fs-readdir-recursive@1.1.0/node_modules/fs-readdir-recursive/index.js:19:7
    at Array.forEach (<anonymous>) {
  errno: -63,
  code: 'ENAMETOOLONG',
  syscall: 'stat',
  path: 'node_modules/@ckb-lumos/lumos/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/debugger/node_modules/@ckb-lumos/common-scripts/node_modules/@ckb-lumos/config-manager/node_modules/@ckb-lumos/base/node_modules/@ckb-lumos/codec/node_modules/@ckb-lumos/bi/node_modules/jsbi/dist/jsbi-cjs.js.map'
}
```
It seems that there is cyclic dependency in ckb-debugger package.

The ckb-debugger has version of "0.21.1" which is very very old and not usable. I think it can removed.

**Comment by XuJiandong** [comment]
And more, after running build commands:
```
pnpm run build
```
I can't find any source map files. It might be caused by this issue.

**Comment by homura** [comment]
Thx for the report, but I'd like to ask the reason for transpiling the code in misc

**Comment by XuJiandong** [comment]
The source maps are missing everywhere. This is what I want to address.

**Comment by homura** [comment]
Hi, could you please try running the following commands at `/projects/lumos` and paste the console output here?

```sh
git rev-parse --short HEAD
pnpm install
pnpm clean
pnpm build
ls packages/lumos/** | grep .map
```

**Comment by XuJiandong** [comment]
```
❯ ls packages/lumos/** | grep .map

packages/lumos/config.d.ts.map
packages/lumos/config.js.map
packages/lumos/helpers.d.ts.map
packages/lumos/helpers.js.map
packages/lumos/index.d.ts.map
packages/lumos/index.js.map
packages/lumos/rpc.d.ts.map
packages/lumos/rpc.js.map
packages/lumos/transaction-manager.d.ts.map
packages/lumos/transaction-manager.js.map
packages/lumos/utils.d.ts.map
packages/lumos/utils.js.map
blockchain.d.ts.map
blockchain.js.map
index.d.ts.map
index.js.map
anyone-can-pay.d.ts.map
anyone-can-pay.js.map
common.d.ts.map
common.js.map
dao.d.ts.map
dao.js.map
index.d.ts.map
index.js.map
secp256k1-blake160-multisig.d.ts.map
secp256k1-blake160-multisig.js.map
secp256k1-blake160.d.ts.map
secp256k1-blake160.js.map
sudt.d.ts.map
sudt.js.map
```
It seems that the vscode hides all these files. It can be found in terminal.
